version: 2

jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: echo "hello, circleci"
      - run: python -V
      - run: pip install awsebcli

