version: 2

jobs:
  build:
    working_directory: /circulate
    docker:
      - image: docker pull pocari/awseb-deployer:latest
    steps:
      - checkout
      - run: echo "hello, circleci"
      - run: python -V
      - run: pip list
      - setup_remote_docker
      - run: docker version
